models:
  - model: C:\Users\LENOVO\Downloads\MMajor\mergekit\OGNO-7B
    parameters:
      density: 0.9
      weight: 0.5
  - model: C:\Users\LENOVO\Downloads\MMajor\mergekit\jaskier-7b-dpo-v5.6
    parameters:
      density: 0.5
      weight: 0.3
merge_method: ties
base_model: C:\Users\LENOVO\Downloads\MMajor\mergekit\jaskier-7b-dpo-v5.6
parameters:
  normalize: true
dtype: float16
